### PR TITLE
make Whisper provider throttle longer after ConnectionError

### PR DESCRIPTION
**Pull request by ayancey**

### CODE REVIEW

**Comment by morpheus65535** [comment]
It seems that there's an issue with list.ts. Can you check it please?

**Comment by morpheus65535** [comment]
I can't find out what's wrong with list.ts format. Can you take a look?

**Comment by ayancey** [comment]
> I can't find out what's wrong with list.ts format. Can you take a look?

Hmm. Can you tell me what the error is?

**Comment by morpheus65535** [comment]
> Hmm. Can you tell me what the error is?

image

**Pull request merged**
