### PR TITLE
Fixed daily download  limit reached exception and wait until next day

### PR DESCRIPTION
**Pull request by redglory**

### CODE REVIEW

**Comment by morpheus65535** [comment]
I'm planning to merge dev to master. Do you see anything else that should be included in this version? Next one could have to wait for a month or two.

**Comment by redglory** [comment]
I'm not seeing anything for know. It's working for me as expected.

If I find any glitch I'll make a pull to dev

**Comment by morpheus65535** [comment]
Thanks!

**Comment by halali** [comment]
Any chance you can also rework OS, your work on legendas is really good

**Comment by redglory** [comment]
> Any chance you can also rework OS, your work on legendas is really good

What kind of work are you thinking of ? And thanks for the compliment :)

**Comment by halali** [comment]
Optimize it same like legendas. Add ipblock exception, i was blocked last week i got 503 error code. And i got service unavailable exception.

**Comment by redglory** [comment]
> Optimize it same like legendas. Add ipblock exception, i was blocked last week i got 503 error code. And i got service unavailable exception.

Just a heads up! HTTP error code 503 might have been just because opensubtitles.org site was down (it happens some times). I can implement the IPAddressBlocked exception but I need to know how OS triggers this. I thin you'll get DownloadLimitReached before you get IP blocked (if this is even a response from their API).

Going to have a look

**Comment by halali** [comment]
No i had blocked ip, admin had to unblock me. I will send you curl once i will be near pc.

**Comment by halali** [comment]
Ok i have got good explanation from OS admin how to detect blocked IP
`Anyway, for javascript blocking, do this:
User is blocked on Cloudflare when:
- response code is 503
- in http reponse header is "server: cloudflare"
- in text you find: "This process is automatic" or "Just a moment"


here is response when user is blocked on cloudflare firewall:
$ curl -vvv https://www.opensubtitles.org/en/search

* Trying 104.26.8.126...

* TCP_NODELAY set

* Connected to www.opensubtitles.org (104.26.8.126) port 443 (#0)

* ALPN, offering h2

* ALPN, offering http/1.1

* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

* successfully set certificate verify locations:

* CAfile: /etc/ssl/cert.pem

CApath: none

* TLSv1.2 (OUT), TLS handshake, Client hello (1):

* TLSv1.2 (IN), TLS handshake, Server hello (2):

* TLSv1.2 (IN), TLS handshake, Certificate (11):

* TLSv1.2 (IN), TLS handshake, Server key exchange (12):

* TLSv1.2 (IN), TLS handshake, Server finished (14):

* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

* TLSv1.2 (OUT), TLS change cipher, Client hello (1):

* TLSv1.2 (OUT), TLS handshake, Finished (20):

* TLSv1.2 (IN), TLS change cipher, Client hello (1):

* TLSv1.2 (IN), TLS handshake, Finished (20):

* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305

* ALPN, server accepted to use h2

* Server certificate:

*subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=opensubtitles.org

*start date: Feb 28 00:00:00 2020 GMT

*expire date: Oct9 12:00:00 2020 GMT

*subjectAltName: host "www.opensubtitles.org" matched cert's "*.opensubtitles.org"

*issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2

*SSL certificate verify ok.

* Using HTTP2, server supports multi-use

* Connection state changed (HTTP/2 confirmed)

* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0

* Using Stream ID: 1 (easy handle 0x7fdab580a800)

> GET /en/search HTTP/2

> Host: www.opensubtitles.org

> User-Agent: curl/7.54.0

> Accept: */*

>

* Connection state changed (MAX_CONCURRENT_STREAMS updated)!`

**Comment by redglory** [comment]
> Ok i have got good explanation from OS admin how to detect blocked IP
> 
> ```
> Anyway, for javascript blocking, do this:
> User is blocked on Cloudflare when:
> - response code is 503
> - in http reponse header is "server: cloudflare"
> - in text you find: "This process is automatic" or "Just a moment"
> 
> 
> here is response when user is blocked on cloudflare firewall:
> $ curl -vvv https://www.opensubtitles.org/en/search
> 
> * Trying 104.26.8.126...
> 
> * TCP_NODELAY set
> 
> * Connected to www.opensubtitles.org (104.26.8.126) port 443 (#0)
> 
> * ALPN, offering h2
> 
> * ALPN, offering http/1.1
> 
> * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> 
> * successfully set certificate verify locations:
> 
> * CAfile: /etc/ssl/cert.pem
> 
> CApath: none
> 
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> 
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> 
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> 
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> 
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> 
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> 
> * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> 
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> 
> * TLSv1.2 (IN), TLS change cipher, Client hello (1):
> 
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> 
> * SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
> 
> * ALPN, server accepted to use h2
> 
> * Server certificate:
> 
> *subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=opensubtitles.org
> 
> *start date: Feb 28 00:00:00 2020 GMT
> 
> *expire date: Oct9 12:00:00 2020 GMT
> 
> *subjectAltName: host "www.opensubtitles.org" matched cert's "*.opensubtitles.org"
> 
> *issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
> 
> *SSL certificate verify ok.
> 
> * Using HTTP2, server supports multi-use
> 
> * Connection state changed (HTTP/2 confirmed)
> 
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> 
> * Using Stream ID: 1 (easy handle 0x7fdab580a800)
> 
> > GET /en/search HTTP/2
> 
> > Host: www.opensubtitles.org
> 
> > User-Agent: curl/7.54.0
> 
> > Accept: */*
> 
> >
> 
> * Connection state changed (MAX_CONCURRENT_STREAMS updated)!
> ```

The import part:
User is blocked on Cloudflare when:
- response code is 503
- in http reponse header is "server: cloudflare"
- in text you find: "This process is automatic" or "Just a moment"

Do you know how much time an IP gets blocked? It would be important to know how much time to throttle this provider.

**Comment by halali** [comment]
We dont know this, you can ask him on discord..

but i think until end of the day and after if still blocked until end of the next day

**Pull request merged**
