### PR TITLE
The official RegieLive API for Bazarr

### PR DESCRIPTION
**Pull request by IonutNeagu**
The regielive provider has been updated to use the official API for Bazarr

### CODE REVIEW

**Comment by morpheus65535** [comment]
@IonutNeagu Hey, thanks for this PR. Whats your relation with RegieLive? I just want to be sure that would be a permanent fix.

@alexandrucatalinene remade this provider from scratch and it's been merged to development branch yesterday (just before you've created this PR. We'll have to see which one is a better choice for both Bazarr and RegieLive.

BTW, PR must be made to development branch.

**Comment by IonutNeagu** [comment]
Hi @morpheus65535, I work at RegieLive and I developed the API for Bazarr.
This way I can adjust the download protection settings more easily so that there are no problems downloading subtitles.

I made the API because I saw the changes made by @alexandrucatalinene and web scraping is forbidden, resulting in the banning of users.

I will make a new PR at the development branch if everything is ok.

**Comment by morpheus65535** [comment]
That's perfect. I'll merge ASAP.

**Comment by alexandrucatalinene** [comment]
Nice!

I'm happy I don't have to maintain that code and that we can have an official API with better results.

@IonutNeagu  do you, by any chance, have any idea why the old API was discontinued and if this new API might have the same fate in the near future?

**Pull request closed without merging**
