### PR TITLE
Fix log filter level check.

### PR DESCRIPTION
**Pull request by Omar007**
Correct errors in the logging changes in #2593.

### CODE REVIEW

**Comment by Omar007** [comment]
As per https://github.com/morpheus65535/bazarr/pull/2593#issuecomment-2351937247, it seems logging paths are potentially not hit in automated tests. There does seem to be a workflow that starts the application but that did not catch my mistake.  
I tried to add something to the `tests` directory to check the `UnwantedWaitressMessageFilter` buut I have no idea if these get run or not :shrug:

**Comment by Omar007** [comment]
Yea doesn't look like those get executed. It should've had a fail on the import for the class, which it did not...

**Review by anderson-oki — APPROVED** [review]

**Comment by morpheus65535** [comment]
@Omar007 Still something wrong here? Using Python 3.8.

```
Traceback (most recent call last):
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/waitress/task.py", line 86, in handler_thread
    self.logger.exception("Exception when servicing %r", task)
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1481, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 811, in filter
    result = f.filter(record)
  File "/Users/morpheus/Desktop/bazarr/bazarr/app/logger.py", line 65, in filter
    if record.level < logging.ERROR:
AttributeError: 'LogRecord' object has no attribute 'level'
```

**Comment by morpheus65535** [comment]
Same thing with 3.11:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/waitress/task.py", line 86, in handler_thread
    self.logger.exception("Exception when servicing %r", task)
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1524, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1643, in handle
    if (not self.disabled) and self.filter(record):
                               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 830, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "/Users/morpheus/Desktop/bazarr/bazarr/app/logger.py", line 65, in filter
    if record.level < logging.ERROR:
       ^^^^^^^^^^^^
AttributeError: 'LogRecord' object has no attribute 'level'. Did you mean: 'levelno'?
```

**Comment by Omar007** [comment]
It should've been fine based on the docs and test file but I guess there's still something else (which also means the test file is setting up the record incorrectly? :confused:  ).  
Not sure what is going on atm, I'll have to set up a local environment again. I'll see if there is anything I can do about having some kind of test going in GitHub as well but I'm not well-versed in either GitHub's CI nor Python so that'll be fun... At this point I do feel like that is a must though as it looks like there is absolutely nothing in place that actually tests anything, nor any kind of process that verifies changes (2 approvals that say the change was OK?)  :'(

**Pull request merged**
