### PR TITLE
Small fix when getting Python bundle path

### PR DESCRIPTION
**Pull request by alexreg**
Amendment to PR #1831 that handles virtual environments properly.

### CODE REVIEW

**Comment by alexreg** [comment]
Incidentally, are you aware that the development branch version does not work? When making an HTTP request, one always gets the following in the log.

```
2022-05-28 03:43:03,300 - app.app                          (29f87f000) :  ERROR (app:1457) - Exception on / [GET]                                                                                       
```

**Comment by morpheus65535** [comment]
> Incidentally, are you aware that the development branch version does not work? When making an HTTP request, one always gets the following in the log.
> 
> ```
> 2022-05-28 03:43:03,300 - app.app                          (29f87f000) :  ERROR (app:1457) - Exception on / [GET]                                                                                       
> ```

Works fine for me. Do you have your dev environment with node setup properly?

**Comment by alexreg** [comment]
@morpheus65535 It's possible something is broken on my system, but it certainly used to work What's the proper setup? And can we enable debug logs? (To know what exact exception occurred.)

**Comment by morpheus65535** [comment]
> @morpheus65535 It's possible something is broken on my system, but it certainly used to work before. What's the proper setup? And can we enable debug logs? (To know what exact exception occurred.)
> 
> Sorry, I probably should have created another issue for this, since it's independent of this PR as far as I can [tell.]

(https://github.com/morpheus65535/bazarr/blob/master/frontend/README.md)

I'll wait for this to be confirm before merging.

**Comment by alexreg** [comment]
@morpheus65535 That's fine. The only small change in this PR is to use the actual location of the Python installation, in case you're using a virtual environment. If you're not using a virtual environment, there's no difference. But by all means, have a test for yourself.

**Comment by alexreg** [comment]
Thanks!

**Pull request merged**
