### PR TITLE
Addition of audio language variables to post processing commands

### PR DESCRIPTION
**Pull request by JpF4E**
As the title says.
It is required for subsync to sync subtitles: need to pass the reference language as argument.

### CODE REVIEW

**Comment by morpheus65535** [comment]
Looks good to me, could you make it to dev branch and I'll run some test on it?

**Comment by JpF4E** [comment]
Is this enough? Guess nothing broke.
Sorry, new to github contributions.

**Comment by morpheus65535** [comment]
audio_language is missing from those ones:
https://github.com/morpheus65535/bazarr/blob/fafeffcfe5e7ead53c60b2b7fb17bae5fd9c1f2c/bazarr/main.py#L1818
https://github.com/morpheus65535/bazarr/blob/fafeffcfe5e7ead53c60b2b7fb17bae5fd9c1f2c/bazarr/main.py#L1953

Make sure you test everything before submitting your PR please.

**Comment by JpF4E** [comment]
You're right, sorry. I missed those two. I fixed it now and tested the manual download both for series and movies.

**Comment by morpheus65535** [comment]
Looks good, thanks!

**Pull request merged**
