### PR TITLE
Add setting to ignore embedded VobSub subtitles

### PR DESCRIPTION
**Pull request by disrupted**
This can be seen as an addition to ignoring embedded PGS subtitles which already exists as a setting. VobSub is another image format which might be undesired as support for it varies. Therefore it's often a good idea to replace it with SRT subs as we do. This PR aims to address that.

### CODE REVIEW

**Comment by morpheus65535** [comment]
Thanks!

**Comment by wastingaeons** [comment]
Thanks for this! However, I wasn't able to get this to work on the files I tested as they report as 'VobSub' and not 'VOBSUB'

**Comment by morpheus65535** [comment]
You're right, I've made an additional commit that should make it works as expected. Please confirm!

**Comment by wastingaeons** [comment]
Confirmed working, thank you!

**Pull request merged**
