### PR TITLE
Prevent Python dock icon appearing on macOS

### PR DESCRIPTION
**Pull request by alexreg**
See [ths comment](https://github.com/python/cpython/issues/92235#issuecomment-1118326297) by a Python maintainer.

Fixes issue #1775.

### CODE REVIEW

**Comment by alexreg** [comment]
Thanks for merging. Do you think this will make it into next release?

**Comment by morpheus65535** [comment]
It will be in tonight beta.

**Comment by alexreg** [comment]
@morpheus65535 Super, thanks.

**Comment by alexreg** [comment]
@morpheus65535 Am I right to say this has made it into *development* but not into *master* yet? Will this make it into the the next beta? That would be great.

**Comment by morpheus65535** [comment]
> @morpheus65535 Am I right to say this has made it into _development_ but not into _master_ yet? Will this make it into the the next beta? That would be great.

Beta is builded from dev branch. It will be in next master in a couple of weeks.

**Comment by alexreg** [comment]
@morpheus65535 Okay, thanks. I presume that will be when the final v1.0.5 comes out.

**Comment by willharris** [comment]
@morpheus65535 @alexreg I've been battling a problem I originally thought was related to #2201 - but it's not, it's related to this change.

I'm not sure if this was originally the case with original Bazarr and Python 3.9 combination when this change was developed (not to mention the Aspell library version), but the changes here completely break virtual environment usage on the Mac for Bazarrr. Regardless of how you start Bazarr, it will insist on trying to install its dependencies in the system.

With the current crop of Homebrew pythons, this will work with 3.10 and 3.11 - though the user won't realise they're writing to the system. But 3.12 will fail - first of all because by default `setuptools` is not available (which can be remedied by `brew install python-setuptools`) but then it runs into the same problem as described in #2201. Rather than removing the `EXTERNALLY-MANAGED` file in the Homebrew python installation, users should be using virtual environments (IMO) - but unfortunately this simply doesn't work on the Mac, due to this change.

The simplest fix I have is to revert the change in `start_bazarr` from calling to `get_python_path()` to simply using `sys.executable`. Then all works as expected. I have yet to see a Dock icon, but perhaps I haven't used a library that triggers it.

In any case, I think the potential presence of a Dock icon is a far smaller evil than a mysteriously broken virtual environment setup on the Mac, especially with later python versions. As it stands, users expecting a 3.12 installation to work will be highly confused, as it simply will not work without modifying the system setup.

**Comment by willharris** [comment]
Here's some shell output to illustrate.

Python 3.11:
```
% brew install python@3.11
...
% pip3.11 list
Package    Version
---------- -------
pip        25.0.1
setuptools 78.1.0
wheel      0.45.1
% python3.11 -m venv .venv
% % .venv/bin/pip install -r requirements.txt
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Requirement already satisfied: setuptools in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (78.1.0)
Collecting lxml<5.0.0,>=4.3.0 (from -r requirements.txt (line 2))
  Using cached lxml-4.9.4-cp311-cp311-macosx_11_0_universal2.whl.metadata (3.7 kB)
Collecting numpy>=1.12.0 (from -r requirements.txt (line 3))
  Using cached numpy-2.2.5-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting webrtcvad-wheels>=2.0.10 (from -r requirements.txt (line 4))
  Using cached webrtcvad_wheels-2.0.14-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting Pillow>=9.0.0 (from -r requirements.txt (line 5))
  Using cached pillow-11.2.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.9 kB)
Using cached lxml-4.9.4-cp311-cp311-macosx_11_0_universal2.whl (8.6 MB)
Using cached numpy-2.2.5-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
Using cached webrtcvad_wheels-2.0.14-cp311-cp311-macosx_11_0_arm64.whl (29 kB)
Using cached pillow-11.2.1-cp311-cp311-macosx_11_0_arm64.whl (3.0 MB)
Installing collected packages: webrtcvad-wheels, Pillow, numpy, lxml
Successfully installed Pillow-11.2.1 lxml-4.9.4 numpy-2.2.5 webrtcvad-wheels-2.0.14
% pip3.11 list
Package    Version
---------- -------
pip        25.0.1
setuptools 78.1.0
wheel      0.45.1
% .venv/bin/pip list
Package          Version
---------------- -------
lxml             4.9.4
numpy            2.2.5
pillow           11.2.1
pip              25.0.1
setuptools       78.1.0
webrtcvad-wheels 2.0.14
% .venv/bin/python bazarr.py
Bazarr starting child process with PID 85067...
/opt/homebrew/Cellar/python@3.11/3.11.12/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
2025-04-24 16:56:17,028 - root                             (1ee1b4f80) :  INFO (init:90) - BAZARR installing requirements...
2025-04-24 16:56:18,696 - root                             (1ee1b4f80) :  INFO (init:102) - BAZARR requirements installed.
2025-04-24 16:56:18,696 - root                             (1ee1b4f80) :  INFO (central:56) - Bazarr is being restarted...
Traceback (most recent call last):
  File "/Users/harris/Workspaces/Bazarr/bazarr/main.py", line 22, in <module>
    from init import *  # noqa E402
    ^^^^^^^^^^^^^^^^^^
  File "/Users/harris/Workspaces/Bazarr/bazarr/init.py", line 160, in <module>
    from app.announcements import get_announcements_to_file
  File "/Users/harris/Workspaces/Bazarr/bazarr/app/announcements.py", line 13, in <module>
    from app.get_providers import get_enabled_providers
  File "/Users/harris/Workspaces/Bazarr/bazarr/app/get_providers.py", line 7, in <module>
    import subliminal_patch
  File "/Users/harris/Workspaces/Bazarr/bazarr/../custom_libs/subliminal_patch/__init__.py", line 8, in <module>
    from .providers import Provider
  File "/Users/harris/Workspaces/Bazarr/bazarr/../custom_libs/subliminal_patch/providers/__init__.py", line 72, in <module>
    mod = importlib.import_module("subliminal_patch.providers.%s" % module_name.lower())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.12/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harris/Workspaces/Bazarr/bazarr/../custom_libs/subliminal_patch/providers/zimuku.py", line 10, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
Deleting restart file...
Terminating child process with PID 85067
Bazarr is restarting...
Bazarr starting child process with PID 85072...
2025-04-24 16:56:24,497 - root                             (356403000) :  INFO (signalr_client:122) - BAZARR trying to connect to Sonarr SignalR feed...
2025-04-24 16:56:24,499 - root                             (35740f000) :  INFO (signalr_client:189) - BAZARR trying to connect to Radarr SignalR feed...
2025-04-24 16:56:24,499 - waitress                         (1ee1b4f80) :  INFO (wasyncore:485) - BAZARR is started and waiting for requests on: http://0.0.0.0:6767
2025-04-24 16:56:24,506 - root                             (35841b000) :  INFO (signalr_client:150) - BAZARR SignalR client for Sonarr is connected and waiting for events.
2025-04-24 16:56:24,512 - root                             (356403000) :  INFO (signalr_client:217) - BAZARR SignalR client for Radarr is connected and waiting for events.
^CClosing database...
Handling keyboard interrupt...
Closing webserver...
2025-04-24 16:56:27,176 - root                             (1ee1b4f80) :  INFO (central:46) - Bazarr is being shutdown...
Deleting stop file...
Terminating child process with PID 85072
Bazarr exited with status code -100.
% pip3.11 list
Package          Version
---------------- -------
lxml             4.9.4
numpy            2.2.5
pillow           11.2.1
pip              25.0.1
setuptools       78.1.0
webrtcvad-wheels 2.0.14
wheel            0.45.1
```

Python 3.12:
```
% brew install python@3.12 python-setuputils
...
% pip3.12 list
Package    Version
---------- -------
pip        25.0.1
setuptools 79.0.1
wheel      0.45.1
% .venv/bin/pip list
Package Version
------- -------
pip     25.0.1
% .venv/bin/pip install -r requirements.txt
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Collecting setuptools (from -r requirements.txt (line 1))
  Using cached setuptools-79.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting lxml<5.0.0,>=4.3.0 (from -r requirements.txt (line 2))
  Using cached lxml-4.9.4-cp312-cp312-macosx_11_0_universal2.whl.metadata (3.7 kB)
Collecting numpy>=1.12.0 (from -r requirements.txt (line 3))
  Using cached numpy-2.2.5-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting webrtcvad-wheels>=2.0.10 (from -r requirements.txt (line 4))
  Using cached webrtcvad_wheels-2.0.14-cp312-cp312-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting Pillow>=9.0.0 (from -r requirements.txt (line 5))
  Using cached pillow-11.2.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (8.9 kB)
Using cached setuptools-79.0.1-py3-none-any.whl (1.3 MB)
Using cached lxml-4.9.4-cp312-cp312-macosx_11_0_universal2.whl (8.6 MB)
Using cached numpy-2.2.5-cp312-cp312-macosx_14_0_arm64.whl (5.2 MB)
Using cached webrtcvad_wheels-2.0.14-cp312-cp312-macosx_11_0_arm64.whl (29 kB)
Using cached pillow-11.2.1-cp312-cp312-macosx_11_0_arm64.whl (3.0 MB)
Installing collected packages: webrtcvad-wheels, setuptools, Pillow, numpy, lxml
Successfully installed Pillow-11.2.1 lxml-4.9.4 numpy-2.2.5 setuptools-79.0.1 webrtcvad-wheels-2.0.14
% .venv/bin/pip list
Package          Version
---------------- -------
lxml             4.9.4
numpy            2.2.5
pillow           11.2.1
pip              25.0.1
setuptools       79.0.1
webrtcvad-wheels 2.0.14
% pip3.12 list
Package    Version
---------- -------
pip        25.0.1
setuptools 79.0.1
wheel      0.45.1
% .venv/bin/python bazarr.py
Bazarr starting child process with PID 85232...
2025-04-24 17:00:32,708 - root                             (1ee1b4f80) :  INFO (init:90) - BAZARR installing requirements...
2025-04-24 17:00:32,886 - root                             (1ee1b4f80) :  ERROR (init:99) - BAZARR requirements.txt installation result: b"error: externally-managed-environment\n\n\xc3\x97 This environment is externally managed\n\xe2\x95\xb0\xe2\x94\x80> To install Python packages system-wide, try brew install\n    xyz, where xyz is the package you are trying to\n    install.\n    \n    If you wish to install a Python library that isn't in Homebrew,\n    use a virtual environment:\n    \n    python3 -m venv path/to/venv\n    source path/to/venv/bin/activate\n    python3 -m pip install xyz\n    \n    If you wish to install a Python application that isn't in Homebrew,\n    it may be easiest to use 'pipx install xyz', which will manage a\n    virtual environment for you. You can install pipx with\n    \n    brew install pipx\n    \n    You may restore the old behavior of pip by passing\n    the '--break-system-packages' flag to pip, or by adding\n    'break-system-packages = true' to your pip.conf file. The latter\n    will permanently disable this error.\n    \n    If you disable this error, we STRONGLY recommend that you additionally\n    pass the '--user' flag to pip, or set 'user = true' in your pip.conf\n    file. Failure to do this can result in a broken Homebrew installation.\n    \n    Read more about this behavior here: <https://peps.python.org/pep-0668/>\n\nnote: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.\nhint: See PEP 668 for the detailed specification.\n"
^CHandling keyboard interrupt...
^CStop doing that! I heard you the first time!
^Z
zsh: suspended  .venv/bin/python bazarr.py
% kill -9 %1
[1]  + killed     .venv/bin/python bazarr.py
```

**Comment by alexreg** [comment]
@willharris I'm not quite sure what issue you're encountering with using a virtual environment, but see the [Homebrew formula for *bazarr*](https://github.com/Homebrew/homebrew-core/blob/90c63eaff5edff68be5b5d17fcfd8d4d329d786b/Formula/b/bazarr.rb), which is working just fine with Python 3.12 right now.

**Comment by willharris** [comment]
Thanks @alexreg. Checking the formula, it looks like they're working around exactly the same problem I'm pointing out here:

https://github.com/Homebrew/homebrew-core/blob/90c63eaff5edff68be5b5d17fcfd8d4d329d786b/Formula/b/bazarr.rb#L65

Their workaround is pretty much the one I'm using, i.e. just use `sys.executable` rather than what `get_python_path()` does on Mac.

**Comment by alexreg** [comment]
@willharris Ah, good to know. In that case I’ve always “tested” that fix and I can gladly assert that the dock icon does not appear.

**Pull request merged**
