### PR TITLE
subssabbz: Small fix

### PR DESCRIPTION
**Pull request by jonudewux**
```
  | Discarding provider subssabbz | an hour ago -- | -- | --
  | Unexpected  error in provider 'subssabbz': Traceback (most recent call last):  File  "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in  list_subtitles_provider    results =  self[provider].list_subtitles(video, provider_languages)  File  "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subssabbz.py",  line 130, in list_subtitles    return [s for l in languages for s in  self.query(l, video)]  File  "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subssabbz.py",  line 125, in query    subtitles = subtitles +  self.download_archive_and_add_subtitle_files(link, language, video)   File  "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subssabbz.py",  line 159, in download_archive_and_add_subtitle_files    raise  ValueError('Not a valid archive')ValueError: Not a valid archive | an hour ago
  | http://subs.sab.bz:80 "GET /forum/index.php?showtopic=17699 HTTP/1.1" 200 None | an hour ago
  | https://subsunacs.net:443  "POST  /search.php?imdbcheck=1&y=2018&a=&c=&d=&g=&m=The+Mule&l=0&u=&t=&action=+++%D0%A2%D1%8A%D1%80%D1%81%D0%B8+++  HTTP/1.1" 200 None | an hour ago
  | Downloading subtitle u'http://subs.sab.bz/forum/index.php?showtopic=17699' | an hour ago
  | Found subtitle link u'http://subs.sab.bz/forum/index.php?showtopic=17699' | an hour ago
  | http://subs.sab.bz:80  "POST  /index.php?upldr=&movie=The+Mule&select-language=2&act=search&release=&yr=2018  HTTP/1.1" 200 None | an hour ago
  | Starting new HTTPS connection (1): subsunacs.net:443

```

### CODE REVIEW

**Comment by morpheus65535** [comment]
Thanks, it seems to be better that way... ;-)

Have you tested it thoroughly?

**Comment by jonudewux** [comment]
I tested it only on that movie, because it seem a easy fix.

**Comment by jonudewux** [comment]
@morpheus65535 
Just run bazzarr with fix on my whole movie/series set and didn't see any issues.

**Comment by morpheus65535** [comment]
Ok thanks, I'll merge it to dev today.

**Pull request merged**
