### PR TITLE
Improve Subdivx provider, handle more exceptions

### PR DESCRIPTION
**Pull request by ngosang**
I prefer to discuss this PR #585 before merging this.

Related #582

### CODE REVIEW

**Comment by halali** [comment]
It's possible do it without editing subliminal_path core?

**Comment by ngosang** [comment]
@halali It's possible if I reuse the `ServiceUnavailable` exception instead of creating a new one. I think the new exception is necessary because there are not exceptions for this use case. The site API changed and the plugin needs to be updated.
Maybe that exception can be included in subliminal_patch. I don't know the author.

**Comment by halali** [comment]
I agree, but its up to morpheus to say if he wants make changes in subliminal_path core...

**Comment by morpheus65535** [comment]
It's fine by me. Anyway we are in the process of porting subliminal_patch to Python v3 so we have to open the hood anyway.

**Comment by morpheus65535** [comment]
Fine by me. I'm waiting on #585 modifications to merge both of them.

**Comment by ngosang** [comment]
> Also you have to add this exception to VALID_THROTTLE_EXCEPTIONS in get_providers

Changed

**Comment by morpheus65535** [comment]
Resolve conflict please.

**Comment by ngosang** [comment]
@morpheus65535 done

**Pull request merged**
