### PR TITLE
Added UnwantedWaitressMessageFilter()

### PR DESCRIPTION
**Pull request by JaiZed**
See Issue #2319 for details

Also includes changes for Issue #2320 (by mistake)

### CODE REVIEW

**Comment by morpheus65535** [comment]
Since you've put both PR in one, it's going to have to wait until I add the UI part of whisperai provider config.

**Comment by halali** [comment]
Why it is called waitress filter when it filtering socketio errors?

And also why is it so complicated and you iterate list[str, list[str]] instead of list of strings?

Also list can be iterated why you make range of len of this list?

**Comment by JaiZed** [comment]
> Why it is called waitress filter when it filtering socketio errors?

It is called the waitress filter because it is filtering the “waitress” log file.
We shouldn’t create a different filter for each type of error; that would lead to an explosion of filters.
> 
> And also why is it so complicated and you iterate list[str, list[str]] instead of list of strings?
>
If you read the code, it’s because the strings correspond to different parts of the log record: the first string is the message and the list[strings] is the possible values from the error part of the exception.
> 
> Also list can be iterated why you make range of len of this list?
It’s because I need to count by 2.
“i” is the message, “i+1” is the corresponding list of matching exception errors 
If you iterate, you will be mixing apples and oranges. Those strings come from different places and should not be mixed together.

**Comment by JaiZed** [comment]
I will split this into 2 PRs as was the original intent.

**Pull request closed without merging**
