### PR TITLE
Bugfix: Add extra try/except in GetRadarrInfo.version()

### PR DESCRIPTION
**Pull request by GilbN**
This adds an extra try/except in GetRadarrInfo.version()
As Radarr returns status code 401 Unauthorized  when using a wrong API key and not status code 200 and `{"error": "Unauthorized"}` like Sonarr does this https://github.com/morpheus65535/bazarr/blob/development/bazarr/utils.py#L323 will create a JSONDecodeError. 

```py
Traceback (most recent call last):
File "/app/bazarr/bin/bazarr/main.py", line 31, in <module>
from get_series import *
File "/app/bazarr/bin/bazarr/get_series.py", line 12, in <module>
from get_episodes import sync_episodes
File "/app/bazarr/bin/bazarr/get_episodes.py", line 12, in <module>
from get_subtitle import episode_download_subtitles
File "/app/bazarr/bin/bazarr/get_subtitle.py", line 43, in <module>
from analytics import track_event
File "/app/bazarr/bin/bazarr/analytics.py", line 18, in <module>
radarr_version = get_radarr_info.version()

File "/app/bazarr/bin/bazarr/utils.py", line 323, in version

radarr_version = requests.get(rv, timeout=60, verify=False, headers=headers).json()['version']

File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I got this error after changing the Radarr API key after Bazarr was already setup.

### CODE REVIEW

**Comment by morpheus65535** [comment]
I see you point but we're loosing the top level try...except catch all exception.

I would try instead to leave the cath all exception and add your other level of try...except but instead of dealing with JSONDecodeError, simply re-raise it so it get catched by the top level catch all exception.

**Comment by GilbN** [comment]
Not sure it I understood what you meant. 

But did you mean something like this?

```python3
            except json.decoder.JSONDecodeError:
                try:
                    rv = url_radarr() + "/api/v3/system/status?apikey=" + settings.radarr.apikey
                    r_api_request = requests.get(rv, timeout=60, verify=False, headers=headers)
                    r_api_request.raise_for_status()
                    radarr_version = r_api_request.json()['version']
                except Exception as e:
                    logging.debug(f'BAZARR cannot get Radarr version. {e}')
                    radarr_version = 'unknown'
```

**Comment by morpheus65535** [comment]
What I had in mind won't work. Maybe something like this?

```

            except json.decoder.JSONDecodeError:
                try:
                    rv = url_radarr() + "/api/v3/system/status?apikey=" + settings.radarr.apikey
                    radarr_version = requests.get(rv, timeout=60, verify=False, headers=headers).json()['version']
                except json.decoder.JSONDecodeError:
                    logging.debug('BAZARR cannot get Radarr version')
                    radarr_version = 'unknown'
            except Exception as e:
                logging.debug('BAZARR cannot get Radarr version')
                radarr_version = 'unknown'
```

**Comment by GilbN** [comment]
> What I had in mind won't work. Maybe something like this?
> 
> ```python
>             except json.decoder.JSONDecodeError:
>                 try:
>                     rv = url_radarr() + "/api/v3/system/status?apikey=" + settings.radarr.apikey
>                     radarr_version = requests.get(rv, timeout=60, verify=False, headers=headers).json()['version']
>                 except json.decoder.JSONDecodeError:
>                     logging.debug('BAZARR cannot get Radarr version')
>                     radarr_version = 'unknown'
>             except Exception as e:
>                 logging.debug('BAZARR cannot get Radarr version')
>                 radarr_version = 'unknown'
> ```

Yup, that works 👍

**Pull request merged**
