### PR TITLE
Adding fix for inconsistent movie/tv naming to yavkanet provider

### PR DESCRIPTION
**Pull request by siankatabg**
Add Superman and Lois

### CODE REVIEW

**Comment by morpheus65535** [comment]
Can you also implement the fix for movies in the same PR?

**Comment by siankatabg** [comment]
I have implemented both, just the movies one is empty(for future use if needed) and I've searched all the titles(both for series and movies) from subs-sabbz/unacs in yavkanet and it doesn't have subtitles for those at all.

**Comment by morpheus65535** [comment]
Sorry my bad, I miss read your changes. I'll get another coffee. ;-)

Thanks!

**Comment by siankatabg** [comment]
Thanks for the fast response 👍🏻

**Pull request merged**
