### PR TITLE
Gestdown Provider: Use new endpoint

### PR DESCRIPTION
**Pull request by Belphemur**
This endpoint rely on caching from cloudflare and will better scale.

Right now, I'm getting around 3M request per day, so I'd like to use the caching as much as possible.

### CODE REVIEW

**Comment by morpheus65535** [comment]
@vitiko98 could you review this PR so we can merge it ASAP if it worsk as expected? Thanks!

**Comment by morpheus65535** [comment]
@Belphemur please rebase on development branch.

**Comment by Belphemur** [comment]
@morpheus65535 Rebased and changed target branch for development

**Comment by Belphemur** [comment]
@vitiko98 If you have any question, don't hesitate to ping me :)

**Comment by Belphemur** [comment]
@morpheus65535 Do you know if @vitiko98 is awol ?

**Comment by morpheus65535** [comment]
> Do you know if @vitiko98 is awol ?

IDK, haven't see him for a while. He seems to be busy with real life.

**Comment by Belphemur** [comment]
Do you think you could try the PR ?

It just this would really improve my life as maintainer of the subtitle provider ^^'

**Comment by vitiko98** [comment]
Sorry for the late response, I didn't see the mention! I'm checking your PR today.

**Review by vitiko98 — APPROVED** [review]
Please consider running tests next time

**Comment by Belphemur** [comment]
@vitiko98 That makes sense, I'll use them next time, thanks for merging it.

**Pull request merged**
