### PR TITLE
Pep Fixes

### PR DESCRIPTION
**Pull request by deathbybandaid**
(re-PRing based on the correct branch)

Tons of pep fixes, also tested locally, and all seems to work fine.

I also want to note that some of the variable and import tweaks don't FIX the issues, but at this time ignore the issues

PEP 8: E722 do not use bare 'except'
E302 expected 2 blank lines, found X
E303 too many blank lines
W293 blank line contains whitespace
W291 trailing whitespace
E203 whitespace before ':'
E231 missing whitespace after ','
E129 visually indented line with same indent as next logical line
E127 continuation line over-indented for visual indent
E111 indentation is not a multiple of four
E117 over-indented
E122 continuation line missing indentation or outdented
E261 at least two spaces before inline comment
E262 inline comment should start with '# '
E251 unexpected spaces around keyword / parameter equals
E265 block comment should start with '# '
W0611 X imported but unused
W0401 'import *' used; unable to detect undefined names
E401 multiple imports on one line
E402 module level import not at top of file
E711 comparison to None should be 'if cond is not None:'
E713 test for membership should be 'not in
E128 continuation line under-indented for visual indent
E129 visually indented line with same indent as next logical line
E701 multiple statements on one line
W0612 local variable X is assigned to but never used
W0404 redefinition of unused import
E741 ambiguous variable name 'l'

### CODE REVIEW

**Comment by morpheus65535** [comment]
Wow! That's a huge PR and really appreciated! I had this in mind for a while but never found the time to do it.

However, I won't merge it because we're in the last weeks before releasing 1.0.0 and I don't want to cause new issues. If you're willing to, I would suggest to make this PR to autonomous branch instead. It's the logical evolution of Bazarr and is what we're actively working on.

**Comment by morpheus65535** [comment]
BTW peewee have a `.is_null(True|False)` method that we should use instead of comparing to None by ourself. Just seen this...

**Comment by deathbybandaid** [comment]
I had a little extra time, and re-broke-out the Commits into what I did

**Comment by deathbybandaid** [comment]
I will look at basing off of the other branch probably Monday

**Comment by morpheus65535** [comment]
> I will look at basing off of the other branch probably Monday

Take your time! We're in no rush of releasing it... there's not even UI for most new stuff! ;-)

**Comment by deathbybandaid** [comment]
@morpheus65535 there are probably things that I'm going to steal from another project I develop for potential future PRs, especially in regards to the cli/startup sequence, database, and logging

https://github.com/fHDHR/fHDHR

**Comment by morpheus65535** [comment]
No problem. However, I suggest you come by Discord dev-community channel so we can talk about it first. :-)

**Pull request closed without merging**
