### PR TITLE
add zimuku subtitle provider

### PR DESCRIPTION
**Pull request by jindaxia**
add a Chinese subtitle site   zimuku
http://www.zimuku.la/

### CODE REVIEW

**Comment by morpheus65535** [comment]
Thanks a lot for this one. Did you thoroughly tested it?

**Comment by jindaxia** [comment]
I only tested about 20 movies , there is nothing unexpected

**Comment by morpheus65535** [comment]
Did you add everything required to enable this provider in wizard and settings?

**Comment by jindaxia** [comment]
no，I only show the hidden dropbox to select it

**Comment by morpheus65535** [comment]
Ok I’ll add the required toggle to make it usable OOTB. Thanks

**Pull request merged**
