### PR TITLE
legendasdivx: using guessit to pick up the right sub in archive

### PR DESCRIPTION
**Pull request by GermanG**
This should solve the issue 2 in my comment https://github.com/morpheus65535/bazarr/issues/834#issuecomment-590104189

### CODE REVIEW

**Comment by morpheus65535** [comment]
For movies, you don't need it?

**Comment by GermanG** [comment]
For episodes is partially solved, it picks the first ocurrence of a season+episode it finds.
For movies is not solved, if we have many subtitles files in the same archive it'll pick the first.
If we aim to get better results, it's going to be a minified version of bazarr: scoring matching subtitules and picking the more likely one. ;)

**Comment by morpheus65535** [comment]
lol ok... :-)

I'm quite uncomfortable having a provider that can give false perfect score that could mess an entire library by upgrading perfectly good subtitles... You don'T feel scared about this?

**Comment by GermanG** [comment]
I get your point, the nature of the scrap based providers make you run that risk, because you'll never know what's exactly inside a given compressed file.
OTOH, I can try to "score" the .srt files in a given archive and pick the best one.

**Comment by GermanG** [comment]
Anyway, for your peace of mind, this PR improves the current quality of the provider.

**Comment by morpheus65535** [comment]
See what you can do about scoring but don't put too much time in it.

**Pull request merged**
