### PR TITLE
logo-redo

### PR DESCRIPTION
**Pull request by goldenpipes**
again :)

full canvas this time!

### CODE REVIEW

**Comment by morpheus65535** [comment]
Those file need to be inverted as the actual images:

- apple-touch-icon.png
- favicon-16x16.png
- favicon-32x32.png
- favicon.ico

**Comment by goldenpipes** [comment]
the `apple-touch-icon.png` is changed for touch bar macbooks.

ill fix the favicon tonight :)

**Comment by goldenpipes** [comment]
to be clear you just want the icon without the circle around it for favicons? and the apple touch icon as well?

**Comment by goldenpipes** [comment]
uploaded the 3 favicon files plus one large favicon file for any extra changes

**Comment by morpheus65535** [comment]
What is expected is an inverted color favicon, that's all.

The actual one looks like: 
image

**Comment by goldenpipes** [comment]
DONE!

**Comment by morpheus65535** [comment]
I don't get why you make white variant... Why not just make favicon the way it is actually (meaning with inverted color surrounded by a black circle)?

**Comment by morpheus65535** [comment]
Feel free to reopen it if you want to complete this PR. Thanks.

**Pull request closed without merging**
