### PR TITLE
Fixes subscene with invalid attribute

### PR DESCRIPTION
**Pull request by soenneker**
This fixes the subscene provider issue since Python dropped unescape

### CODE REVIEW

**Comment by halali** [comment]
Don't think this version check iw necessary as we dont support python2 anymore. Just let imported html instead using six if six is issue maker for you.

**Comment by morpheus65535** [comment]
Agreed. Please make your code Python 3.7/3.8 compatible only. No need to deal with Python 2.x.

**Comment by soenneker** [comment]
👍 should be good to go

**Comment by morpheus65535** [comment]
Thanks!

**Pull request merged**
