### PR TITLE
Added support for embedded mp4 subtitles

### PR DESCRIPTION
**Pull request by sekkr1**
Embedded subtitle detection now uses ffprobe from ffmpeg to list embedded subtitles which includes support for mp4 with fallback to enzyme mkv only detection in case a compatible ffprobe executable was not found for the platform.

### CODE REVIEW

**Comment by morpheus65535** [comment]
It looks very good and I'm testing it at the moment. As you don't check for file extension before trying to analyze a file, I'm curious about how ffmpeg will react if he cannot analyze the file. Wjhat will be the return for an unrecognized file format?

**Comment by sekkr1** [comment]
It will just return a non zero exit code raising an exception that's caught by the except in list_subtitles file

**Comment by morpheus65535** [comment]
Ok. Can you add an "if" to only analyze .mkv file to enzyme because it raise an exception as it is.

Also, can you change the base branch to development please? Thanks!

**Comment by sekkr1** [comment]
Updated.

**Pull request merged**
