### PR TITLE
Fixes #773

### LINKED ISSUE #773: subs4series, subz HTTPError
I am receiving the following errors:

Throttling subs4series for 10 minutes, until 20/01/25 06:42, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.subs4series.com/search_report.php?search=lady%20dynamite&searchType=1

Throttling subz for 10 minutes, until 20/01/25 06:42, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: https://www.subz.xyz/typeahead/lady%20dynamite'

Propably same case with #767 issue

Bazarr Version:0.8.4.1
Sonarr Version:3.0.3.688
Radarr Version:3.0.0.2564
Operating System:Linux-4.15.0-72-generic-x86_64-with
Python Version:3.8.1

Just find that subz.xyz its closed so nothing to do with bazarr....
Or maybe had change url....dont know any other info

### PR DESCRIPTION
**Pull request by pkoutsias**
Fixes subs4free and subs4series providers
Removes subz provider

### CODE REVIEW

**Comment by morpheus65535** [comment]
Thanks for the fix. What happen if someone had subz provider enabled? Does it get removed from config file? Will it throw an error/exception every time a search for subtitles occur?

**Comment by pkoutsias** [comment]
Trying it on my installation for half a day now, no exceptions yet.

**Comment by morpheus65535** [comment]
> Trying it on my installation for half a day now, no exceptions yet.

Does it get removed from config file?

**Comment by babos123** [comment]
I am here:
Bazarr Version:0.8.4.3
Sonarr Version:3.0.3.750
Radarr Version:3.0.0.2784
Operating System:Linux-4.15.0-72-generic-x86_64-with
Python Version:3.8.2

never worked the fix for subs4free and subs4series
Wondering if it just me or something else.
Thanks anyway for your work pkoutsias!

**Comment by morpheus65535** [comment]
Please provide a debug log to reproduce the issue.

**Comment by babos123** [comment]
Ok i will today

**Comment by morpheus65535** [comment]
@babos123 BTW open an issue for this please.

**Pull request merged**
