### PR TITLE
fixed retries to get download link to avoid throttling

### PR DESCRIPTION
**Pull request by redglory**
The while loop could throttle legendasdivx. Just pass to next subtitle.

Also implemented 403 - Forbidden return

### CODE REVIEW

**Comment by redglory** [comment]
Sorry, forgot to select correct branch :)

**Comment by morpheus65535** [comment]
Just tell me once this PR is completed and I'll review it.

**Comment by redglory** [comment]
Done! It's hard to treat all exceptions before we get them :)

You can review this pull requests now. 

Thanks

**Comment by morpheus65535** [comment]
Thanks!

**Pull request merged**
