### PR TITLE
Update to apprise v1.6.0

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Modeled this PR after 07f601f407ef5b9e6fe0b0db842f3bec8c9916b0, which was a response to #2163.

Apprise changelog: https://github.com/caronc/apprise/releases

Highlights are the addition of these notification services:

* v1.6.0 
    * Notifiarr
* v1.5.0
    * Pushy
    * PushDeer
    * PushMe
    * RSyslog
* v1.4.5
    * WhatsApp
    * Burst SMS

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
Tried this out locally in my Docker container for Bazarr, works well with Notifiarr!

As an FYI, if you want to try out Notifiarr, I used the URL provided by Notifiarr.com like so:

Screenshot 2023-11-07 at 10 30 31 PM

**Comment by morpheus65535** [comment]
Why does it need the _yaml module patch?

**Comment by jeffbyrnes** [comment]
@morpheus65535 when I `pip install apprise`, along with different versions of a number of dependencies, that gets added. So I assumed it’s needed & included it here.

**Comment by jeffbyrnes** [comment]
Your comment has reminded me to check the logs though, and now that I’ve had this set up for a little bit, it seems to be struggling, so looks like there’s more to puzzle out here:

```
2023-11-07 22:28:52,427 - apprise (7f78eba9db38) :  WARNING (NotifyNotifiarr:226) - Dropped invalid channel (General) specified.
2023-11-07 22:28:52,428 - apprise (7f78eba9db38) :  WARNING (NotifyNotifiarr:280) - There were no Notifiarr channels to notify.
2023-11-07 22:29:28,748 - apprise (7f78eac1fb38) :  WARNING (NotifyNotifiarr:226) - Dropped invalid channel (General) specified.
2023-11-07 22:29:28,749 - apprise (7f78eac1fb38) :  WARNING (NotifyNotifiarr:280) - There were no Notifiarr channels to notify.
2023-11-07 22:38:10,616 - app.app (7f78f2c7bb38) :  ERROR (app:1741) - Exception on /api/system/settings [POST]
```

**Comment by morpheus65535** [comment]
> @morpheus65535 when I `pip install -U apprise`, along with newer versions of a number of dependencies, that gets added. So I assumed it’s needed & included it here. The other dependencies are already present, so to minimize the impact of this, I left them unchanged. Thankfully, it appears to work without those being upgraded.

I'll speak with Chris, the dev behind apprise, on Discord about it to be sure we need it.

**Comment by morpheus65535** [comment]
> Your comment has reminded me to check the logs though, and now that I’ve had this set up for a little bit, it seems to be struggling, so looks like there’s more to puzzle out here:
> 
> ```
> 2023-11-07 22:28:52,427 - apprise (7f78eba9db38) :  WARNING (NotifyNotifiarr:226) - Dropped invalid channel (General) specified.
> 2023-11-07 22:28:52,428 - apprise (7f78eba9db38) :  WARNING (NotifyNotifiarr:280) - There were no Notifiarr channels to notify.
> 2023-11-07 22:29:28,748 - apprise (7f78eac1fb38) :  WARNING (NotifyNotifiarr:226) - Dropped invalid channel (General) specified.
> 2023-11-07 22:29:28,749 - apprise (7f78eac1fb38) :  WARNING (NotifyNotifiarr:280) - There were no Notifiarr channels to notify.
> 2023-11-07 22:38:10,616 - app.app (7f78f2c7bb38) :  ERROR (app:1741) - Exception on /api/system/settings [POST]
> ```

I don't think you've configured it properly. Check the wiki: https://github.com/caronc/apprise/wiki/Notify_notifiarr

**Comment by jeffbyrnes** [comment]
Annnnd now I'm rolling that API key 🤦🏻

**Comment by morpheus65535** [comment]
image

Don't expect it to works if you don't use it as the developer documented it.

**Comment by jeffbyrnes** [comment]
@morpheus65535 I tried that initially, and it _doesn’t_ work that way. If I enter it as that `notifiarr://` style URL, and click “Test”, no test notification reaches my Discord server. Here’s what the logs show when I set it to `notifiarr://{api_key}/General`:

```
bazarr  | 2023-11-13 19:22:13,428 - apprise                          (7f78eb88bb38) :  WARNING (NotifyNotifiarr:226) - Dropped invalid channel (General) specified.
bazarr  | 2023-11-13 19:22:13,428 - apprise                          (7f78eb88bb38) :  WARNING (NotifyNotifiarr:280) - There were no Notifiarr channels to notify.
```

If I use the channel ID instead of its name:

```
bazarr  | 2023-11-13 19:23:44,351 - apprise                          (7f78e9135b38) :  WARNING (NotifyNotifiarr:365) - Failed to send Notifiarr Verification Failed. notification: , error=401.
```

When I copy in what Notifiarr.com provides, the `jsons://` URL, I can send a test notification successfully.

The fact that the `jsons` URL tests correctly, while the `notifiarr` one doesn’t, suggests to me that it’s the correct string to use.

All this said, I certainly don’t expect you to support somebody else’s library, but I am wondering if it’s some kind of interaction between what Bazarr passes to Apprise.

**Comment by jeffbyrnes** [comment]
Well hmm.

On a lark, I tried using the non-integration-specific API key for Notifiarr.com, with the Discord channel ID, and it worked.

Not my favorite, but I suspect this is a bug to file with Apprise, not here.

**Comment by jeffbyrnes** [comment]
Opened caronc/apprise#999 to clarify the wiki docs, so others have an easier time than I did.

**Comment by morpheus65535** [comment]
> Opened [caronc/apprise#999](https://github.com/caronc/apprise/issues/999) to clarify the wiki docs, so others have an easier time than I did.

You can talk with Chris on Discord also: https://discord.com/channels/558793703356104724/558810264485494786

**Comment by jeffbyrnes** [comment]
Chris merged in caronc/apprise#999, and this has been working well for me once I sorted out the correct syntax for configuring it, and that it needs to use a generic, not integration-specific, Notifiarr API key.

If you’re good with it, it’d be great to see this merge in & be released!

**Comment by morpheus65535** [comment]
I'll be happy to merge your PR once the next version including this fix is released.

**Comment by jeffbyrnes** [comment]
So [my fix is already included](https://github.com/caronc/apprise/issues/999#issuecomment-1813723161), it’s a change to the [Apprise → Notifiarr wiki docs](https://github.com/caronc/apprise/wiki/Notify_notifiarr). No new release of Apprise is needed, my fixes are already live 🙂

**Comment by morpheus65535** [comment]
Oh sorry, I was under the impression you had changed something in the code also.

I'll merge this then!

**Pull request merged**
