### PR TITLE
Reduce CPU, Disk and Memory usage

### PR DESCRIPTION
**Pull request by ngosang**
This code does exactly the same as the old code but in a smarter way reducing resources usage.
* Old code starts a new thread every second. **This task is very expensive in CPU and Memory**. From Python doc => Multiple threads live in the same process in the same space, each thread will do a specific task, have its own code, own stack memory, instruction pointer, and share heap memory.
* Old code tries to read 2 files from disk every second. This operation is not expensive, but the hard drive can't go to sleep.
* New code doesn't use threads and only reads the files when the Bazarr process ends.

CPU usage in Idle state reduced from 38.9 ms/s to 5.4 ms/s

In my machine, Bazarr was responsible for creating 2/3 of all new threads.
image

Related #289

### CODE REVIEW

**Comment by carlosflorencio** [comment]
This change decreased the CPU usage by 120% on my system. 

Nice one 👍

**Comment by morpheus65535** [comment]
Thanks @ngosang ! If you have time, I would be happy to have a word with you on Discord. We really need some help to optimize Bazarr. Some stuff have been there for almost 2 years when I started learning Python. Your help would be a great addition to the team. I hope to see you soon!

**Comment by ngosang** [comment]
@morpheus65535 thank you for the invitation! Sorry, I'm already involved in too many projects and I don't have free time. I'm using Bazarr myself, so, if I found bugs or make changes in my custom build I will open issues or PRs. Thank you for the software, it's working well for me.

About the code, I didn't see much but..
* I think the project has too many dependencies/libraries for the task it does. This is hard to maintain and increases the memory usage (I think it's high too). Follow the KISS principle.
* Make unit tests, the code base is big enough to break things easily. You can configure Github/Travis to run the test before merging the PRs.
* Migrating to Python3 can be an opportunity to do the things better this time. Just take it easy, I already did several ports like Medusa, qBittorent ... and it takes a lot of time. More advices:
  * Python3 has very good support for unicode/internationalization, http and asynchronous events. This will improve performance and you can remove some libs like six, webencoding, urlib3...
  * Work in a new branch, never in master because it will block the whole project for months. You can create a milestone/label to merge the PRs in the right branch.
  * First try to make the current code to work in python3. There is a tool called py2to3 that will help, but the result code is nasty and sometimes doesn't work. I recommend you to replace the libs with the new version, I'm sure most of them are already working in python3.
  * Compiling in python3 doesn't mean it's working well. You will find a ton of bugs in the ported code, but will be easy to fix.
  * After doing this changes you will have a clear view of the whole code and you can start working in the code refactor.

Maybe some day we meet in Discord. Regards!

**Comment by morpheus65535** [comment]
Thank you very much for the feedback mate! Feel free to contribute when you want. :-)

**Pull request merged**
