### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by goldenpipes**
re-did the logo to make it higher res.

cheers!

### CODE REVIEW

**Comment by morpheus65535** [comment]
I've reverted this commit because Bazarr logo do not fill the canvas. Can you produce the same images but where the logo use maximum space? Thanks.

**Comment by goldenpipes** [comment]
hey ive been away but yeah i can re-do these filling the canvas!

**Comment by morpheus65535** [comment]
No problem. BTW I’ve updated the logo64 and logo128 last week in dev branch. They are way better.

**Comment by goldenpipes** [comment]
Awesome I'll check it out!

**Comment by goldenpipes** [comment]
Looks good man! I've sent a new pr your way if u wanna use em.

**Pull request merged**
