### PR TITLE
fix: use path mappings for video_analyzer operations

### PR DESCRIPTION
**Pull request by tnyeanderson**
Fixes: #2512 

I have not tested this solution as I'm not very familiar with the code base. This is just a potential solution I see to the issue described. There may be a better way to do this, or I may be doing it completely wrong :)

### CODE REVIEW

**Comment by tnyeanderson** [comment]
I've now tested this solution, and it does work as expected.

**Comment by morpheus65535** [comment]
Ok, getting back to this after 2 weeks, sorry for the delay. I've looked into this again and you were right. If you want to rebase on dev branch, I'll merge your PR ASAP. Thanks!

**Comment by tnyeanderson** [comment]
Should be good to go, thanks! :)

**Comment by morpheus65535** [comment]
Thanks!

**Pull request merged**
