### PR TITLE
Add subsunacs.net and subs.sab.bz providers

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
PR for #208

### CODE REVIEW

**Comment by dimitrov-adrian** [comment]
Should be fixed now.

**Comment by morpheus65535** [comment]
You need to move new providers to subliminal_patch if you want them to be available when we list providers: https://github.com/dimitrov-adrian/bazarr/blob/aafc55f3cbfaa4b1ba8564d83840b67c0fd15607/bazarr/main.py#L228

**Comment by morpheus65535** [comment]
subs.sab.bz is working fine. I cannot get any result from subsunacs.net. Can you confirm it work on your side? I havent tried English BTW, only Bulgarian.

**Comment by dimitrov-adrian** [comment]
Locally on macOS seems to works, but found that on Docker on Synology, it won't and got error related to unrar libary

```
Unexpected error in provider 'subsunacs': Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) 
 File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subsunacs.py", line 132, in list_subtitles return [s for l in languages for s in self.query(l, video)]
 File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subsunacs.py", line 127, in query subtitles = subtitles + self.download_archive_and_add_subtitle_files('https://subsunacs.net' + link, language, video) 
 File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subsunacs.py", line 157, in download_archive_and_add_subtitle_files return self.process_archive_subtitle_files( RarFile(archive_stream), language, video ) 
 File "/app/bazarr/bazarr/../libs/rarfile.py", line 666, in __init__ self._parse() 
 File "/app/bazarr/bazarr/../libs/rarfile.py", line 858, in _parse self._file_parser.parse() 
 File "/app/bazarr/bazarr/../libs/rarfile.py", line 973, in parse self._parse_real() 
 File "/app/bazarr/bazarr/../libs/rarfile.py", line 1047, in _parse_real self.process_entry(fd, h)
 File "/app/bazarr/bazarr/../libs/rarfile.py", line 1460, in process_entry cmt = self._read_comment_v3(item, self._password) 
 File "/app/bazarr/bazarr/../libs/rarfile.py", line 1414, in _read_comment_v3 inf.file_size, inf.flags, inf.CRC, psw, inf.salt) 
 File "/app/bazarr/bazarr/../libs/rarfile.py", line 2747, in rar3_decompress p = custom_popen(cmd) 
 File "/app/bazarr/bazarr/../libs/rarfile.py", line 2816, in custom_popen raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
 RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='/app/bazarr/bin/Linux/x86_64/UnRAR/unrar')
```

**Comment by dixonbg** [comment]
It appears, that "manual search"->"download" and "link to the subs page" do not work for these providers.
Bazarr version 0.7.2.1
Python version 2.7.15
Sonarr version 2.0.0.5322
Radarr version 0.2.0.1293
Operating system Linux-4.18.20-unRAID-x86_64-with

**Comment by morpheus65535** [comment]
@dixonbg Can you open an issue about this please?

**Pull request merged**
