### PR TITLE
Adds GreekSubtitles, Subs4Free, Subs4Series, SubZ and XSubs providers

### PR DESCRIPTION
**Pull request by pkoutsias**

### CODE REVIEW

**Comment by morpheus65535** [comment]
Thank you very much for this PR! I'll look into it soon. Is it stable enough to be merger or does it need more testing and optimization on your side?

**Comment by pkoutsias** [comment]
I've been testing it in my setup for some days now and all providers seem stable. For now, I think they are ok.

**Comment by halali** [comment]
I can see as possible issue that, there are used import from subliminal instead subliminal_patch... I'm not sure if it can cause any issue.

**Comment by pkoutsias** [comment]
I can see other providers also importing subliminal or even mixing subliminal and subliminal_patch. @morpheus65535 what do you think?

**Comment by morpheus65535** [comment]
To be honest, I have no clue. I’ve never develop a provider. What are those provider mixing patched and not?

**Comment by morpheus65535** [comment]
Merged to dev, thanks!

**Comment by jimger** [comment]
@pkoutsias Any chance u add the vipsubs.gr?
Also any chance add the release info from xsubs?

**Pull request merged**
