### PR TITLE
Fix podnapisi results parsing

### PR DESCRIPTION
**Pull request by tomislav**

### CODE REVIEW

**Comment by morpheus65535** [comment]
Thanks!

**Comment by tomislav** [comment]
On second thought, using `or` might be correct after all.

```
if not xml.find('pagination/results') or not int(xml.find('pagination/results').text):
    logger.debug('No subtitles found')
    break
```

The condition is checking two things:

* If xml.find('pagination/results') returns None.
* If the text of xml.find('pagination/results') is 0 or an empty string

If either of these conditions is true, it means no subtitles were found. Using `and` could cause a potential exception when trying to access the `text` property.

Sorry, I got a little lost in all the not's and and's :)

Still not sure why it's not working with `or` though.

**Comment by tomislav** [comment]
Yeah, after more testing this PR is not going to work out. Please revert while I investigate more.

**Comment by morpheus65535** [comment]
Done

**Pull request merged**
