### PR TITLE
Fixed duplicate IDs in languages profile items

### PR DESCRIPTION
**Pull request by morpheus65535**
- [x] Fixed duplicate languages profile items IDs for those without cutoff and implemented health issue notifications for those with cutoff.
- [x] Fix frontend to be able to edit remaining languages profiles, reassign IDs and confirm cutoff before hitting save button.

### CODE REVIEW

**Review by JaiZed — APPROVED** [review]
It all looks good to me.

**Review by anderson-oki — APPROVED** [review]

**Comment by morpheus65535** [comment]
@anderson-oki sanitize should be run only if the profile has duplicate items ID, right?

**Comment by anderson-oki** [comment]
> @anderson-oki sanitize should be run only if the profile has duplicate items ID, right?

Not really, it also sanitize tag null to undefined and we need that forever.

**Comment by morpheus65535** [comment]
> > @anderson-oki sanitize should be run only if the profile has duplicate items ID, right?
> 
> Not really, it also sanitize tag null to undefined and we need that forever.

Is cutoff preserve on edit if we assign new id to items?

**Review by anderson-oki — APPROVED** [review]

**Pull request merged**
