### PR TITLE
Update subdivx.py

### PR DESCRIPTION
**Pull request by danilogd**
Subdix changed the text on the download links to "Bajar subtitulo ahora" and the script is looking for "bajar". With this change Subdivx starts working again.

### CODE REVIEW

**Comment by morpheus65535** [comment]
Make it to dev branch please! Thanks!

**Comment by GermanG** [comment]
I'm not sure if this conflicts with #806 (I'm on the phone right now)
@danilogd did you check if the dev branch works?

**Comment by danilogd** [comment]
I confirm that #806 solve the problem. I am closing this commit because is redundant.

**Comment by morpheus65535** [comment]
Thanks for the help nevertheless!

**Comment by tribugames** [comment]
Dont work
subdvix

**Comment by morpheus65535** [comment]
@tribugames are you running dev branch? if not you won't benefit from the fix yet.

**Comment by tribugames** [comment]
Run fine now on master new releases thank you

**Pull request closed without merging**
