### PR TITLE
Some fixes on providers subdvix, legendasdivx and bsplayer.

### PR DESCRIPTION
**Pull request by GermanG**
Hello!
This merge requests has:
- 2 fixes for LegendasDivxs  
- Adding release_info for bsplayer and subdivx (I used the "Filename" from bsplayer and the description from subdivx) I don't know if this is the proper place to put that info, but from my own usage I wanted to know that information when downloading manually.
- Removing unused imports from bsplayer and legendasdivx (tested both again)

Let me know if you prefer making many merge requests instead of one (for small fixes)

### CODE REVIEW

**Comment by morpheus65535** [comment]
If it's not to complicated, I would prefer having one PR by provider next time. Just in case we want to rollback on only one of them. Thanks!

**Comment by estimadarocha** [comment]
Can you guys review if the legendasdivx is correctly working it doesn't seen to find anything. Thanks

**Comment by GermanG** [comment]
@estimadarocha can you provide an example?
I want to reproduce your issue.
@morpheus65535 how do you reproduce this? I normally test against my own home install, but that means if I want to simulate someone else's issue to get the series/movie they have. 🤔

**Comment by estimadarocha** [comment]
@GermanG if you have the time and the oportunity I can provide you access to my system... Maybe TeamViewer... I have account with legendasdivx and in a week it have downloaded no more than 10 episodes. If I search manually on the site I got 90% of the results of my library

**Comment by GermanG** [comment]
I'm not a portuguese speaker - maybe portuñol but you will get hurt by it - so I don't use the plugin myself. (On second thought I should enable it and let it work, it doesn't hurt to have an extra sub)
Let me know an specific example ("I have the file xxx, the plugin does not work, I go to the site and search for xxx and here it is!")
Here's how it works (so far): The plugin looks for the filename exactly as you have it, if it finds it it'll show up. I was thinking if I had 0 results I'd go for something like Name Season Episode (on series) and Name on movies, but that'd also means to paginate something the plugin does not do either.

**Comment by halali** [comment]
@estimadarocha do you renaming your files? If yes what software do that rename and how looks renamed file

**Comment by estimadarocha** [comment]
Yes I rename then on sonarr... And I make sure all files have the scene releasegroup in naming of the file

**Comment by estimadarocha** [comment]
Episode path is: /tv/The 100/Season 6/The 100 - S06E13 - The Blood of Sanctum WEBDL-1080p AMRAP.mkv
Scenename is: The.100.S06E13.iNTERNAL.1080p.WEB.X264-AMRAP

**Comment by estimadarocha** [comment]
Episode path is: /tv/Chernobyl/Season 1/Chernobyl - S01E05 - Vichnaya Pamyat WEBDL-1080p NTb.mkv
Scenename is: Chernobyl.S01E05.Vichnaya.Pamyat.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb

Another example

**Comment by GermanG** [comment]
@estimadarocha https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=search&query=the+100+s06e13 
Does not show anything, neither looking for "the 100 s06", only "the 100" shows anything. 
It may be a good idea to do the same thing I did (look for full name, then series S+E, then series S, then series), on the other hand the plugin might be ending up hammering the site.

**Comment by estimadarocha** [comment]
Yeah chernobyl it's there

https://www.legendasdivx.pt/modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=chernobyl+s01e05+vichnaya+pamyat

**Comment by GermanG** [comment]
Yup, but if you look for "Chernobyl.S01E05.Vichnaya.Pamyat.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb" it's empty.

Chernobyl.S01E05.Vichnaya.Pamyat is basically the series sxxexx episodename.

**Comment by estimadarocha** [comment]
So is there something that can be tweaked on bazarr to make it search correctly?

**Comment by estimadarocha** [comment]
I remember to use legendasdivx plug-in on kodi and it have the option to look for exact file name and it works flawless. Maybe it do 2 search one to search for series sxxexx episode name and them after the results it choose the exact one

**Comment by morpheus65535** [comment]
@GermanG I test the same way you do: with my own setup. I don't have synthetic test.

**Comment by GermanG** [comment]
@estimadarocha Take a look at  #801 also if you want to follow up this, please open an issue. It's easier for me to follow up than a closed PR.

Regards.

**Pull request merged**
