### PR TITLE
add cookies option for addic7ed to avoid captcha

### PR DESCRIPTION
**Pull request by aarnaud**
Support authentication by using cookie obtain in browser after manually login and resolved recaptcha
Screenshot from 2022-01-04 20-40-16

### CODE REVIEW

**Comment by morpheus65535** [comment]
Looks nice, thanks!

Could you add a fake default value to give the user an idea of should be put there (like you did in the screenshot)?

**Comment by aarnaud** [comment]
I updated the PR with a default value as example, but if it set by default it will not work. because when cookie is not empty the user/pass isn't use.

Screenshot from 2022-01-05 20-20-57

**Comment by morpheus65535** [comment]
Tu passes me voir sur Discord?

**Comment by aarnaud** [comment]
So by using `keyNameOverride`

Screenshot from 2022-01-05 21-15-19

**Comment by morpheus65535** [comment]
> So by using `keyNameOverride`
> 
> Screenshot from 2022-01-05 21-15-19

That's way better than my previous suggestion, thanks! :-)

**Comment by TheToto** [comment]
Did it still work for you @aarnaud ?
I copy paste the `document.cookies` of addic7ed website, and i always have this error : 

```
HTTPSConnectionPool(host='www.addic7ed.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...
```

**Comment by aarnaud** [comment]
There is also rate limit addic7ed, maybe you are just temporary blocked.

**Comment by TheToto** [comment]
> There is also rate limit addic7ed, maybe you are just temporary blocked.

Yes, it's surely the rate limit, i'll retry later.
Thanks for your reply !

**Pull request merged**
