### PR TITLE
add subtitri.nekur.net and subtitri.id.lv subtitle providers

### PR DESCRIPTION
**Pull request by girtskokars**
add two latvian subtitle providers (http://subtitri.nekur.net/ and http://subtitri.id.lv/)

### CODE REVIEW

**Comment by morpheus65535** [comment]
Thanks!

Did you run many test?

**Comment by girtskokars** [comment]
i've been using/testing them for the past month or so and everything seems to be working without any issues

**Comment by morpheus65535** [comment]
In manual search, Nekur return a generic URL instead of the specific subtitles page. Can you correct that please?

**Comment by morpheus65535** [comment]
In fact, even if both return result in manual search, neither manual or automatic download download any subtitles...

**Comment by girtskokars** [comment]
> In manual search, Nekur return a generic URL instead of the specific subtitles page. Can you correct that please?

unlike most subtitle web pages, http://subtitri.nekur.net/ has no separate page (`page_link`) for each subtitle, only a direct download link. should i use that instead? seeing as that `page_link` appears in manual search as the provider, i opted to link the entry with the provider link not the direct download link.


> In fact, even if both return result in manual search, neither manual or automatic download download any subtitles...

just tested with some additional movies on the dev branch - manual and automatic downloads seem to work fine. could you point to the subtitle or movie that doesn't download so i can try to reproduce it. maybe it's something to do with the individual subtitle.

**Comment by morpheus65535** [comment]
In that case, change `page_link` to the actual srt file URL.

My test is run with `Jumanji.Welcome.to.the.Jungle.2017.720p.BluRay.H264.AAC-RARBG` scenename requesting for `lv` subtitles. An English subtitles can be downloaded from opensubtitles without any issue.

**Comment by morpheus65535** [comment]
Thanks you for this PR!

**Pull request merged**
