### PR TITLE
 Fix video hash not being computed when using Napisy24 provider 

### PR DESCRIPTION
**Pull request by MoshiMoshi0**
If a user had `opensubtitles` provider disabled the hash would never be computed.

### CODE REVIEW

**Comment by morpheus65535** [comment]
Can you achieve the same result without editing core.py?

**Comment by MoshiMoshi0** [comment]
Not really, this is the only place where the hashes are computed. Why is that a problem?

**Comment by morpheus65535** [comment]
Because I have to move it upstream in SZ to be sure it's not lost when we update subliminal_patch from SZ. @pannal don't want to bring the new providers we develop in Bazarr to SZ so it require a little more ingenuity...

**Comment by MoshiMoshi0** [comment]
Well I dont know how should I do this then. This means that you cant add new providers that compute hashes? Subliminal will say that the video is not valid if there is no hash that is set in `required_hash`.

What should I do?

**Comment by morpheus65535** [comment]
@pannal could we have your input on that matters?

**Comment by MoshiMoshi0** [comment]
Just a side note but looks like the default settings force skip the hash. The setting `use_scenename` (default `True`) is sent to `scan_video` as `dont_use_actual_file` which skips computation of hashes:

https://github.com/morpheus65535/bazarr/blob/a0e7e63286f2a9af929bfcc21280f1193588c952/libs/subliminal_patch/core.py#L540-L565

**Comment by MoshiMoshi0** [comment]
v0.7.5 has been released with Napisy24 provider but this still needs to be fixed. I dont see any proper way other than modifying core.py, I guess I could move the hash computation into `get_matches` but I dont think providers should be touching the files at all.

**Comment by morpheus65535** [comment]
@Pannal could we get to an end on this topic? Thanks.

**Comment by pannal** [comment]
> Just a side note but looks like the default settings force skip the hash. The setting `use_scenename` (default `True`) is sent to `scan_video` as `dont_use_actual_file` which skips computation of hashes:
> 
> https://github.com/morpheus65535/bazarr/blob/a0e7e63286f2a9af929bfcc21280f1193588c952/libs/subliminal_patch/core.py#L540-L565

That's right. Not sure how to fix this on first glance, but shouldn't be too complicated.

**Comment by pannal** [comment]
You're setting `required_hash` - is the hash *required* for the search?

**Comment by MoshiMoshi0** [comment]
Yes Napisy24 only uses the hash and the file name for search. Both are required.
Thanks for the merge.

**Pull request merged**
