### PR TITLE
Add variables to post-processing.

### PR DESCRIPTION
**Pull request by drikqlis**
Add 4 variables to custom post-processing script:

- subtitle_id - Provider ID of the subtitles file.
- provider - Provider of the subtitles file.
- series_id - Sonarr series ID. Empty if movie.
- episode_id - Sonarr episode ID or Radarr movie ID.

When uploading manually I put placeholders into subtitle_id and provider because it is unknown.

### CODE REVIEW

**Comment by morpheus65535** [comment]
Thanks for the PR. If you want to add this, it must be done for movies also. Can you add this?

**Comment by drikqlis** [comment]
episode_id contains Radarr movie id if the file is a movie or Sonarr episode id if the file is an episode, similarly to for example {{episode_name}} which contains move/episode name. series_id is empty if the file is a movie. Unless you have something else in mind?

**Comment by morpheus65535** [comment]
Sorry for the delay! That's perfectly fine for me. Please just make sure you don't have conflict and I'll merge it.

**Comment by drikqlis** [comment]
Should be fine now.

**Comment by morpheus65535** [comment]
Thanks!

**Pull request merged**
